# Copyright 2026 Snowflake Inc.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""How SQLite differs from the portable default.

Pinned amalgamation ≥3.39 has native ``RIGHT`` / ``FULL OUTER JOIN``; we emit them as-is
(``visit_join_query``). ``QUALIFY`` becomes a subquery + ``WHERE``.
Type spelling uses SQLite affinity names.

**Type affinity.** SQLite assigns affinity to *table* columns from their declared type, but
expressions (window functions, arithmetic, compound ``UNION ALL`` result columns) often have
*no* affinity. Views expose expression affinity, not the base table's
(https://www.sqlite.org/datatype3.html §3.2–3.3.1). Equivalence rewrites that turn a base
table into views/windows/unions therefore change how comparisons coerce — e.g.
``1462169534 > c_txt`` can match a real ``TEXT`` column and miss the same value through a
view. Wrapping every projected column in ``CAST(... AS <declared type>)`` restores the
declared affinity on every ``CREATE … AS`` boundary so base and equivalent agree.
"""

from __future__ import annotations

from eqgen.core.catalog import Named
from eqgen.core.statement import Statement
from eqgen.core.types import SqlType
from eqgen.dialects.sqlite.ast import (
    SqliteAnalyzeIndexObject,
    SqliteAttachObject,
    SqliteExprIndexObject,
    SqliteGeneratedObject,
    SqliteIndexObject,
    SqliteNestedMaterializedCteQuery,
    SqliteQueryVisitor,
    SqliteRecursiveCteQuery,
    SqliteSetupVisitor,
    SqliteStrictObject,
    SqliteWithoutRowidIndexObject,
    SqliteWithoutRowidObject,
)
from eqgen.dialects.sqlite.types_sql import sqlite_type
from eqgen.equivalence.ast import ExceptAllQuery, IntersectAllQuery, JoinQuery, ProjectionItem, SelectQuery, UnionAllQuery
from eqgen.equivalence.emitter import QueryRenderer, SqlEmitter, _projection_sql
from eqgen.ir.expr import AggregateCall, AggregateFunction, Mod, ValueCodec, ValueCodecRoundTrip
from eqgen.ir.render import PostgresSpelling, Spelling, UnsupportedForDialect


class SqliteSpelling(PostgresSpelling):

    def value_codec_sql(self, node: ValueCodecRoundTrip) -> str:
        """Verified on SQLite 3.53.4. ``unhex`` needs the explicit CAST back to TEXT — it returns a
        BLOB, which would change the declared column type and fail the pre-gate on types alone.

        SQLite has no base64. That **raises** rather than falling through to ``super()``: the
        inherited PostgreSQL spelling would render ``convert_from(decode(encode(…)))``, which SQLite
        also does not have, so every round would die as unbuildable and the only thing standing
        between us and that would be a weight of 0 in a config file. Refusing here means the
        configuration and the spelling cannot drift apart silently.
        """
        inner = self.expr(node.arg)
        if node.codec is ValueCodec.JSON_PACK:
            return f"json_extract(json_object('v', {inner}), '$.v')"
        if node.codec is ValueCodec.HEX:
            return f"CAST(unhex(hex({inner})) AS TEXT)"
        raise UnsupportedForDialect(f"SQLite has no {node.codec.value} codec")

    def type_sql(self, data_type: SqlType) -> str:
        return sqlite_type(data_type)

    def mod_sql(self, node: Mod) -> str:
        return f"(({self.expr(node.operand)}) % {node.modulus})"

    def aggregate_sql(self, node: AggregateCall) -> str:
        """SQLite has no ``ANY_VALUE``; write it as ``MAX``.

        Exact rather than approximate here. ``ANY_VALUE`` is only generated by the key-channel
        reducers, which group *copies of one base row*, so every row in a group holds the same value
        and every choice function over the group returns it — ``MAX`` included.

        Spelled here rather than handled by disabling the builder, because the builder's semantics do
        hold on SQLite; only the function name does not. Postgres carried this same rewrite for
        servers older than 16 and dropped it at 18.4, which is how SQLite came to be left emitting a
        function it does not have: the reducers were enabled and every round they touched died as
        "no such function: ANY_VALUE" — unbuildable, silently discarded, retried on a new seed.

        Contrast TiDB, which *has* ``ANY_VALUE`` and still disables the reducers: there the pick is
        plan-dependent, so the semantics genuinely do not hold and weight 0 is right.
        """
        if node.function is AggregateFunction.ANY_VALUE:
            return f"MAX({self.expr(node.arg)})"
        return super().aggregate_sql(node)


def _cast_projection_sql(item: ProjectionItem, spelling: Spelling) -> str:
    """``CAST(<expr> AS <affinity type>) AS <alias>`` — see module docstring."""
    inner = spelling.expr(item.expr)
    return f"CAST({inner} AS {sqlite_type(item.data_type)}) AS {item.alias}"


def _cast_signature_sql(signature: list[Named[SqlType]], source_sql: str) -> str:
    """Re-project *source_sql* with a CAST per column so compound/select-star keeps affinity."""
    select_list = ", ".join(
        f"CAST({named.alias} AS {sqlite_type(named.target)}) AS {named.alias}" for named in signature
    )
    return f"SELECT {select_list} FROM ({source_sql}) AS eq_aff"


class SqliteQueryRenderer(QueryRenderer, SqliteQueryVisitor[str]):
    def visit_select_query(self, query: SelectQuery) -> str:
        if query.qualify is None:
            return self._select_with_affinity(query)
        if query.projection is None:
            raise ValueError("SQLite QUALIFY lowering needs an explicit projection")
        distinct = "DISTINCT " if query.distinct else ""
        where = f" WHERE {self._spelling.expr(query.predicate)}" if query.predicate is not None else ""
        group = (
            " GROUP BY " + ", ".join(self._spelling.expr(key) for key in query.group_by)
            if query.group_by is not None
            else ""
        )
        q_expr = self._spelling.expr(query.qualify)
        # Keep the qualify probe un-cast (boolean); affinity-cast the exposed columns only.
        inner_proj = ", ".join(_projection_sql(item, self._spelling) for item in query.projection)
        inner = (
            f"SELECT {distinct}{inner_proj}, ({q_expr}) AS eq_q "
            f"FROM {query.source.ref_sql()}{where}{group}"
        )
        outer_list = ", ".join(
            f"CAST({item.alias} AS {sqlite_type(item.data_type)}) AS {item.alias}" for item in query.projection
        )
        body = f"SELECT {outer_list} FROM ({inner}) AS eq_qsrc WHERE eq_q"
        if query.order_by is None:
            return body
        order = ", ".join(self._spelling.expr(key) for key in query.order_by)
        return f"SELECT {outer_list} FROM ({body} ORDER BY {order}) AS eq_ord"

    def _select_with_affinity(self, query: SelectQuery) -> str:
        where = f" WHERE {self._spelling.expr(query.predicate)}" if query.predicate is not None else ""
        distinct = "DISTINCT " if query.distinct else ""
        group = (
            " GROUP BY " + ", ".join(self._spelling.expr(key) for key in query.group_by)
            if query.group_by is not None
            else ""
        )
        if query.projection is None:
            # Expand ``*`` so each column can carry a CAST (SELECT * cannot).
            select_list = ", ".join(
                f"CAST({named.alias} AS {sqlite_type(named.target)}) AS {named.alias}"
                for named in query.get_signature()
            )
        else:
            select_list = ", ".join(_cast_projection_sql(item, self._spelling) for item in query.projection)
        body = f"SELECT {distinct}{select_list} FROM {query.source.ref_sql()}{where}{group}"
        if query.order_by is None:
            return body
        order = ", ".join(self._spelling.expr(key) for key in query.order_by)
        outer = select_list if query.projection is not None else ", ".join(
            f"CAST({named.alias} AS {sqlite_type(named.target)}) AS {named.alias}"
            for named in query.get_signature()
        )
        return f"SELECT {outer} FROM ({body} ORDER BY {order}) AS eq_ord"

    def visit_union_all_query(self, query: UnionAllQuery) -> str:
        # Compound SELECT affinity is indeterminate (§3.3.1). CAST the concatenated result.
        compound = " UNION ALL ".join(f"SELECT * FROM {branch.ref_sql()}" for branch in query.branches)
        return _cast_signature_sql(query.get_signature(), compound)

    def visit_except_all_query(self, query: ExceptAllQuery) -> str:
        compound = (
            f"SELECT * FROM {query.left.ref_sql()} "
            f"EXCEPT ALL "
            f"SELECT * FROM {query.right.ref_sql()}"
        )
        return _cast_signature_sql(query.get_signature(), compound)

    def visit_intersect_all_query(self, query: IntersectAllQuery) -> str:
        compound = (
            f"SELECT * FROM {query.left.ref_sql()} "
            f"INTERSECT ALL "
            f"SELECT * FROM {query.right.ref_sql()}"
        )
        return _cast_signature_sql(query.get_signature(), compound)

    def visit_join_query(self, query: JoinQuery) -> str:
        # eqgen pins SQLite ≥3.53, which has native RIGHT/FULL OUTER JOIN (since 3.39).
        # Do not rewrite to LEFT — that collapses the planner surface we want to hunt.
        select_list = ", ".join(_cast_projection_sql(item, self._spelling) for item in query.projection)
        where = f" WHERE {self._spelling.expr(query.predicate)}" if query.predicate is not None else ""
        if query.join_type.upper() == "CROSS":
            on = ""
        else:
            if query.condition is None:
                raise ValueError("a join must have an ON condition")
            on = f" ON {self._spelling.expr(query.condition)}"
        return (
            f"SELECT {select_list} FROM {query.left.ref_sql()} {query.left_alias} "
            f"{query.join_type} JOIN {query.right.ref_sql()} {query.right_alias}{on}{where}"
        )

    def visit_sqlite_recursive_cte_query(self, query: SqliteRecursiveCteQuery) -> str:
        cols = ", ".join(query.out_cols)
        src = query.source.ref_sql()
        name = query.cte_name
        compound = (
            f"WITH RECURSIVE {name} AS ("
            f"SELECT {cols} FROM {src} "
            f"UNION ALL "
            f"SELECT {cols} FROM {name} WHERE FALSE"
            f") SELECT {cols} FROM {name}"
        )
        return _cast_signature_sql(query.get_signature(), compound)

    def visit_sqlite_nested_materialized_cte_query(self, query: SqliteNestedMaterializedCteQuery) -> str:
        cols = ", ".join(query.out_cols)
        src = query.source.ref_sql()
        compound = (
            f"WITH {query.inner_name} AS MATERIALIZED (SELECT {cols} FROM {src}), "
            f"{query.outer_name} AS MATERIALIZED (SELECT {cols} FROM {query.inner_name}) "
            f"SELECT {cols} FROM {query.outer_name}"
        )
        return _cast_signature_sql(query.get_signature(), compound)


class SqliteEmitter(SqlEmitter, SqliteSetupVisitor[list[Statement]]):
    def __init__(self) -> None:
        super().__init__(query_renderer=SqliteQueryRenderer(spelling=SqliteSpelling()))

    def visit_sqlite_index_object(self, node: SqliteIndexObject) -> list[Statement]:
        cols = ", ".join(node.out_cols)
        unique = "UNIQUE " if node.unique else ""
        where = f" WHERE {node.where_sql}" if node.where_sql else ""
        return [
            Statement(
                f"CREATE {unique}INDEX {node.index_name} ON {node.body_ref} ({node.target}){where}"
            ),
            Statement(f"CREATE VIEW {node.name} AS SELECT {cols} FROM {node.body_ref}"),
        ]

    def visit_sqlite_analyze_index_object(self, node: SqliteAnalyzeIndexObject) -> list[Statement]:
        cols = ", ".join(node.out_cols)
        where = f" WHERE {node.where_sql}" if node.where_sql else ""
        return [
            Statement(f"CREATE INDEX {node.index_name} ON {node.body_ref} ({node.target}){where}"),
            Statement(f"ANALYZE {node.body_ref}"),
            Statement(f"CREATE VIEW {node.name} AS SELECT {cols} FROM {node.body_ref}"),
        ]

    def visit_sqlite_attach_object(self, node: SqliteAttachObject) -> list[Statement]:
        cols = ", ".join(node.out_cols) if node.out_cols else "*"
        # Copy into main then DETACH: SQLite caps attachments at 10, and views cannot
        # reference other schemas anyway.
        return [
            Statement(f"ATTACH DATABASE ':memory:' AS {node.alias}"),
            Statement(
                f"CREATE TABLE {node.alias}.{node.mirror} AS SELECT {cols} FROM {node.body_ref}"
            ),
            Statement(
                f"CREATE TABLE {node.name} AS SELECT {cols} FROM {node.alias}.{node.mirror}"
            ),
            Statement(f"DETACH DATABASE {node.alias}"),
        ]

    def visit_sqlite_without_rowid_object(self, node: SqliteWithoutRowidObject) -> list[Statement]:
        defs = ", ".join(node.col_defs)
        cols = ", ".join(node.out_cols)
        return [
            Statement(
                f"CREATE TABLE {node.table_name} ({defs}, PRIMARY KEY ({node.pk_col})) WITHOUT ROWID"
            ),
            Statement(f"INSERT INTO {node.table_name} ({cols}) SELECT {cols} FROM {node.body_ref}"),
            Statement(f"CREATE VIEW {node.name} AS SELECT {cols} FROM {node.table_name}"),
        ]

    def visit_sqlite_generated_object(self, node: SqliteGeneratedObject) -> list[Statement]:
        defs = ", ".join(node.col_defs)
        cols = ", ".join(node.out_cols)
        kind = "STORED" if node.stored else "VIRTUAL"
        return [
            Statement(
                f"CREATE TABLE {node.table_name} ("
                f"{defs}, "
                f"{node.gen_col} INTEGER GENERATED ALWAYS AS ({node.gen_of}) {kind})"
            ),
            Statement(f"INSERT INTO {node.table_name} ({cols}) SELECT {cols} FROM {node.body_ref}"),
            Statement(f"CREATE VIEW {node.name} AS SELECT {cols} FROM {node.table_name}"),
        ]

    def visit_sqlite_strict_object(self, node: SqliteStrictObject) -> list[Statement]:
        defs = ", ".join(node.col_defs)
        cols = ", ".join(node.out_cols)
        return [
            Statement(f"CREATE TABLE {node.table_name} ({defs}) STRICT"),
            Statement(f"INSERT INTO {node.table_name} ({cols}) SELECT {cols} FROM {node.body_ref}"),
            Statement(f"CREATE VIEW {node.name} AS SELECT {cols} FROM {node.table_name}"),
        ]

    def visit_sqlite_expr_index_object(self, node: SqliteExprIndexObject) -> list[Statement]:
        cols = ", ".join(node.out_cols)
        return [
            Statement(f"CREATE INDEX {node.index_name} ON {node.body_ref} ({node.expr_sql})"),
            Statement(f"CREATE VIEW {node.name} AS SELECT {cols} FROM {node.body_ref}"),
        ]

    def visit_sqlite_without_rowid_index_object(self, node: SqliteWithoutRowidIndexObject) -> list[Statement]:
        defs = ", ".join(node.col_defs)
        cols = ", ".join(node.out_cols)
        return [
            Statement(
                f"CREATE TABLE {node.table_name} ({defs}, PRIMARY KEY ({node.pk_col})) WITHOUT ROWID"
            ),
            Statement(f"INSERT INTO {node.table_name} ({cols}) SELECT {cols} FROM {node.body_ref}"),
            Statement(f"CREATE INDEX {node.index_name} ON {node.table_name} ({node.index_col})"),
            Statement(f"CREATE VIEW {node.name} AS SELECT {cols} FROM {node.table_name}"),
        ]
